### PR TITLE
Updated inventory calculations for new recipe data model

### PR DESCRIPTION
**Pull request by sguichard**
The inventory calculations are different after running the migration script - about 20 rows change for both Valencia and Alabama. 

See the differences here - https://docs.google.com/spreadsheets/d/1Lp9oC_-hEZkHeOP3Aw1A5QGkfm90An5bwhwMtWqaJWA/edit?usp=sharing

### CODE REVIEW

**Comment by mayanb** [comment]
I just tried running your command after pulling production and it errored out

**Comment by sguichard** [comment]
@mayanb I just pushed a fix for that bug and the script now runs successfully for me.

**Comment by mayanb** [comment]
are we sure this really the change we want? wouldn't this mean we are using the same taskingredient across different inputs with different team_inventories? 
Like if we have Task 1432 (created by alabama) which has 4 inputs with the same product and process type and 2 of those inputs have a team_inventory of valencia
then wouldn't this command just create 1 taskIngredient which combines all 4 inputs and sets the team_inventory for the TaskIngredient to the last input it checked?

**Comment by mayanb** [comment]
also why do we want to filter out ship or deliver? Don’t those need to have their inputs showing up too?

**Pull request closed without merging**
