### PR TITLE
Aggregate activity log rows by product type when flag is passed

### PR DESCRIPTION
**Pull request by sguichard**

### CODE REVIEW

**Review by mayanb — CHANGES_REQUESTED** [review]
can you please distinct the list of products that it's returning?

**Comment by sguichard** [comment]
It looks like adding distinct to ArrayAgg is only supported with Django 2.0 (see https://docs.djangoproject.com/en/2.0/ref/contrib/postgres/aggregates/# versus https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/aggregates/)

How about if we filter for uniqueness on the frontend instead? We could remove the product name and id from the response since the front end currently only displays the product code. We're still sending duplicate data, but looking at a month of Alabama data the response side is only 61kb, even with all the duplicate product codes.

**Comment by mayanb** [comment]
hm im guessing we're probably still going to need the product code since we'll use the product code and process codes to get the list of tasks to show when you click on viewalltasks for a row
I would prefer filtering it on the backend but I don't super care. Couldn't you just filter it in the serializer? e.g. 
	def get_product_types(self, activity):
		x = list(zip(activity['product_type_ids'],activity['product_type_codes']))
		y = list(set(x))
		return [
			{
				'id': y[i][0],
				'code': y[i][1],
			} for i in range(len(y))]

**Comment by sguichard** [comment]
Damn, I implemented my own uniqueness filter because my GitHub email notification didn't show your updated comment. But I think it's equivalent. Thanks for your help!

**Review by mayanb — APPROVED** [review]

**Pull request merged**
